services:
   resume_postgres:
      image: postgres:16-alpine
      container_name: resume_postgres
      environment:
         POSTGRES_USER: postgres
         POSTGRES_PASSWORD: Parvati..18
         POSTGRES_DB: resumedb
      volumes:
         - resumepgdata:/var/lib/postgresql/data
      ports:
         - "5432:5432"
   
  
   resume_node_api:
      build:
         context: ../backend
         dockerfile: ../backend/Dockerfile
      container_name: resume_node_api
      depends_on:
         - "resume_postgres"
      environment:
         PORT: 3000
         DATABASE_URL: 
         ACCESS_TOKEN_SECRET: 
         ACCESS_TOKEN_EXPIRY: 15m
         REFRESH_TOKEN_SECRET: 
         REFRESH_TOKEN_EXPIRY: 7d
         CLOUDINARY_CLOUD_NAME: 
         CLOUDINARY_API_KEY: 
         CLOUDINARY_API_SECRET: 
         NODE_ENV: development
         COOKIE_SECURE: false
         AI_SERVICE_URL: http://host.docker.internal:8000
         REDIS_HOST : 
         REDIS_PASSWORD : 
         REDIS_USERNAME : 
         REDIS_PORT : 
      volumes:
         - ../backend:/app
         - /app/node_modules
      ports:
         - "3000:3000"
         - "5555:5555"

volumes:
   resumepgdata:
